# docker-compose.yml
version: '3.8'

services:
  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    restart: always
    depends_on:
      confero_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./auth_service:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DATABASE_URL=postgresql://confero_user:confero_pass@confero_db:5432/confero_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminpassword
      - RABBITMQ_VHOST=/
      - JWT_SIGNING_KEY=your-shared-jwt-signing-key-here

  room_service:
    build:
      context: ./room_service
    container_name: room_service
    restart: always
    depends_on:
      confero_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8001:8001"
    expose:
      - "8001"
    volumes:
      - ./room_service:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001 --noreload"
    environment:
      - DATABASE_URL=postgresql://confero_user:confero_pass@confero_db:5432/confero_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminpassword
      - RABBITMQ_VHOST=/
      - JWT_SIGNING_KEY=your-shared-jwt-signing-key-here

  confero_db:
    image: postgres:15
    container_name: confero_db
    restart: always
    environment:
      POSTGRES_DB: confero_db
      POSTGRES_USER: confero_user
      POSTGRES_PASSWORD: confero_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U confero_user -d confero_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=adminpassword
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 15s
      timeout: 20s
      retries: 5

  notification_service:
    build:
      context: ./notification_service
    container_name: notification_service
    restart: always
    depends_on:
      confero_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8003:8003"
    volumes:
      - ./notification_service:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8003 & python notifications/rabbitmq_consumer.py"
    environment:
      - DATABASE_URL=postgresql://confero_user:confero_pass@confero_db:5432/confero_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminpassword
      - RABBITMQ_VHOST=/
      - JWT_SIGNING_KEY=your-shared-jwt-signing-key-here

volumes:
  postgres_data:
  rabbitmq_data: