# docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - confero_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    restart: always
    depends_on:
      confero_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./auth_service:/app
    networks:
      - confero_network
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DATABASE_URL=postgresql://confero_user:confero_pass@confero_db:5432/confero_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminpassword
      - RABBITMQ_VHOST=/
      - JWT_SIGNING_KEY=a-string-secret-at-least-256-bits-long
      - CELERY_BROKER_URL=amqp://admin:adminpassword@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  room_service:
    build:
      context: ./room_service
    container_name: room_service
    restart: always
    depends_on:
      confero_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      auth_service:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - "8001:8001"
    volumes:
      - ./room_service:/app
      - ./media:/app/media
    networks:
      - confero_network
    command: >
      sh -c "daphne -b 0.0.0.0 -p 8001 room_service.asgi:application & python rooms/rabbitmq_consumer.py & wait"
    environment:
      - DJANGO_SETTINGS_MODULE=room_service.settings
      - DATABASE_URL=postgresql://confero_user:confero_pass@confero_db:5432/confero_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminpassword
      - RABBITMQ_VHOST=/
      - JWT_SIGNING_KEY=a-string-secret-at-least-256-bits-long
      - AUTH_SERVICE_URL=http://auth_service:8000/api/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health/"]
      interval: 10s
      timeout: 5s
      retries: 3
  confero_db:
    image: postgres:15
    container_name: confero_db
    restart: always
    environment:
      POSTGRES_DB: confero_db
      POSTGRES_USER: confero_user
      POSTGRES_PASSWORD: confero_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - confero_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U confero_user -d confero_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=adminpassword
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - confero_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 15s
      timeout: 20s
      retries: 5

  notification_service:
    build:
      context: ./notification_service
    container_name: notification_service
    restart: always
    depends_on:
      confero_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      auth_service:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - "8003:8003"
    volumes:
      - ./notification_service:/app
    networks:
      - confero_network
    command: >
      sh -c "daphne -b 0.0.0.0 -p 8003 notification_service.asgi:application & python notifications/rabbitmq_consumer.py"
    environment:
      - DATABASE_URL=postgresql://confero_user:confero_pass@confero_db:5432/confero_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminpassword
      - RABBITMQ_VHOST=/
      - JWT_SIGNING_KEY=a-string-secret-at-least-256-bits-long
      - AUTH_SERVICE_URL=http://auth_service:8000/api/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003"]
      interval: 10s
      timeout: 5s
      retries: 3

  chat_service:
    build:
      context: ./chat_service
    container_name: chat_service
    restart: always
    depends_on:
      confero_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      auth_service:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - "8002:8002"
    volumes:
      - ./chat_service:/app
    networks:
      - confero_network
    command: >
      sh -c "daphne -b 0.0.0.0 -p 8002 chat_service.asgi:application"
    environment:
      - DATABASE_URL=postgresql://confero_user:confero_pass@confero_db:5432/confero_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminpassword
      - RABBITMQ_VHOST=/
      - JWT_SIGNING_KEY=a-string-secret-at-least-256-bits-long
      - AUTH_SERVICE_URL=http://auth_service:8000/api/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002"]
      interval: 10s
      timeout: 5s
      retries: 3

  video_service:
    build:
      context: ./video_service
    container_name: video_service
    restart: always
    depends_on:
      confero_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      auth_service:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - "8004:8004"
    volumes:
      - ./video_service:/app
    networks:
      - confero_network
    command: >
      sh -c "daphne -b 0.0.0.0 -p 8004 video_service.asgi:application"
    environment:
      - DJANGO_SETTINGS_MODULE=video_service.settings
      - DATABASE_URL=postgresql://confero_user:confero_pass@confero_db:5432/confero_db
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=adminpassword
      - RABBITMQ_VHOST=/
      - JWT_SIGNING_KEY=a-string-secret-at-least-256-bits-long
      - AUTH_SERVICE_URL=http://auth_service:8000/api/
      - REDIS_HOST=redis
      - REDIS_PORT=6379


volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  confero_network:
    driver: bridge