# Generated by Django 5.1.7 on 2025-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='friend_requestId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
