# Generated by Django 5.1.8 on 2025-04-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_friend_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
