# Generated by Django 5.1.8 on 2025-04-12 10:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_group_chat', models.BooleanField(default=False)),
                ('participants', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['participants'], name='chats_chatg_partici_b25ab0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_email', models.EmailField(max_length=254)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video')], default='text', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('media_file', models.FileField(blank=True, max_length=255, null=True, upload_to='chat_media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_by', models.JSONField(default=list)),
                ('chat_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chatgroup')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['chat_group', 'created_at'], name='chats_messa_chat_gr_e7c92a_idx'), models.Index(fields=['sender_email'], name='chats_messa_sender__cf44a8_idx')],
            },
        ),
    ]
