# Generated by Django 5.1.7 on 2025-03-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='room_thumbnails/'),
        ),
    ]
