# Generated by Django 5.1.7 on 2025-04-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='creator_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
