# Generated by Django 5.1.7 on 2025-04-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_creator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='creator_email',
            field=models.EmailField(max_length=254),
        ),
    ]
