# Generated by Django 5.1.7 on 2025-04-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
