# Generated by Django 5.1.8 on 2025-04-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_room_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='creator_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['slug'], name='rooms_room_slug_3e98b7_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['creator_id'], name='rooms_room_creator_9ef40f_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['name'], name='rooms_room_name_46fb51_idx'),
        ),
    ]
