# Generated by Django 5.1.8 on 2025-04-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_room_creator_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_live',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_live'], name='rooms_room_is_live_0b8c30_idx'),
        ),
    ]
