# Generated by Django 5.1.8 on 2025-04-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_room_is_live_room_rooms_room_is_live_0b8c30_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCallSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.IntegerField()),
                ('creator_email', models.EmailField(max_length=254)),
                ('participants', models.JSONField(default=list)),
                ('scheduled_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='rooms.room')),
            ],
        ),
        migrations.DeleteModel(
            name='RoomInvite',
        ),
        migrations.AddIndex(
            model_name='videocallschedule',
            index=models.Index(fields=['scheduled_time'], name='rooms_video_schedul_4a4e64_idx'),
        ),
        migrations.AddIndex(
            model_name='videocallschedule',
            index=models.Index(fields=['is_notified'], name='rooms_video_is_noti_73f802_idx'),
        ),
    ]
