# Generated by Django 5.1.7 on 2025-03-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_photo',
            new_name='profile_photo',
        ),
    ]
