# Generated by Django 5.1.7 on 2025-03-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
